# Generated by Django 2.2.12 on 2020-06-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(default=0, verbose_name='Código Comuna')),
                ('com_name', models.CharField(max_length=20, verbose_name='Nombre Comuna')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_id', models.IntegerField(blank=True, verbose_name='Código País')),
                ('pais_name', models.CharField(max_length=20, verbose_name='Nombre País')),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField(default=0, verbose_name='Código Región')),
                ('reg_name', models.CharField(max_length=20, verbose_name='Nombre Región')),
                ('reg_pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Pais')),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='parentesco',
            field=models.CharField(max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Comuna'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fono',
            field=models.CharField(max_length=12, verbose_name='Fono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Region'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sange',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=10, verbose_name='sange'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer')], max_length=8, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='Prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_id', models.IntegerField(default=0, verbose_name='Código Provincia')),
                ('prov_name', models.CharField(max_length=20, verbose_name='Nombre Provincia')),
                ('prov_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Region')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='prov_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Prov'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meds.Pais'),
            preserve_default=False,
        ),
    ]
