# Generated by Django 2.2.12 on 2020-06-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_auto_20200622_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='region',
        ),
        migrations.AlterField(
            model_name='alergias',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
        ),
        migrations.AlterField(
            model_name='patologias',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Paciente'),
        ),
    ]
